### ISSUE TITLE
Assistance Needed: Error and Clarification on Model Weights for AFHQ Training in Python

### ISSUE THREAD

**Issue by Sourabs-kms** [steven202/semantic_adv_via_dm#3]
Hello,

I encountered an error while running the command python main_afhq_train.py --attack --config afhq.yml --exp ./runs_train_afhq_0122 --n_test_img 4 --t_0 500 --n_inv_step 40 --n_test_step 40 >> log_train_afhq_0122.txt. The error message is as follows:

arduino
Copy code
ERROR - main_afhq_train.py - 2024-01-14 03:48:04,342 - Traceback (most recent call last):
  File "main_afhq_train.py", line 325, in main
    runner.attack()
  File "/workspace/algorithm/semantic_adv_via_dm-main/diffusionclip_afhq_train.py", line 127, in attack
    ckpt = torch.load(model_path)
  File "/opt/conda/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'dm_afhq_model.pth'
Could you please provide guidance on where to download the dm_afhq_model.pth file? Additionally, I'm unsure about how to appropriately adjust the diffusion model weights downloaded earlier with the code. Are there any specific modifications required in the code to ensure compatibility?

Your assistance in clarifying these matters would be greatly appreciated. Thank you!

**Comment by steven202** [comment]
Hi, 

The dm_afhq_model.pth is retraining from the afhqdog_p2.pt, I think. 
Unfortunately, you need to follow the standard training process of a diffusion model for dm_afhq_model.pth, or you can just try to attack the dog category.

Thank you.

**Comment by Sourabs-kms** [comment]
Hello, I would like to ask if you involved dm_afhq_model.pth in this code at the beginning. When I ran this code block, I still reported an error. I have configured the pre-trained model weight you mentioned.

CUDA_VISIBLE_DEVICES=0,1 python main_afhq_train.py --attack              --config afhq.yml                     --exp ./runs_train_afhq_0122                  --n_test_img 4                         --t_0 500                               --n_inv_step 40                         --n_test_step 40      >> log_train_afhq_0202.txt
INFO - main_afhq_train.py - 2024-02-02 13:49:40,189 - Using device: cuda
INFO - main_afhq_train.py - 2024-02-02 13:49:40,190 - Exp instance id = 112982
INFO - main_afhq_train.py - 2024-02-02 13:49:40,190 - Exp comment = 
INFO - main_afhq_train.py - 2024-02-02 13:49:40,190 - Config =
ERROR - main_afhq_train.py - 2024-02-02 13:49:43,493 - Traceback (most recent call last):
  File "main_afhq_train.py", line 327, in main
    runner.attack()
  File "/workspace/algorithm/adv_se/diffusionclip_afhq_train.py", line 130, in attack
    ckpt = torch.load(model_path)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'dm_afhq_model.pth'

**Comment by steven202** [comment]
For afhq, as stated in the appendix of the paper, we can only generate dog images.
We use model weights from https://github.com/gwang-kim/DiffusionCLIP.
