### ISSUE TITLE
diffusionclip_afhq_train.py  error

### ISSUE THREAD

**Issue by mac2win** [steven202/semantic_adv_via_dm#5]
diffusionclip_afhq_train.py  
The code segment starts from line 120

 elif self.config.data.dataset in ["FFHQ", "AFHQ", "IMAGENET"]:
                if self.config.data.dataset == "AFHQ" and model_path == None:
                    model_path = "dm_afhq_model.pth"
                    with open(os.path.join(self.args.image_folder, f'{"train"}_log.txt'), "a+") as file1:
                        file1.write(f"load afhq model path")
                    print("load afhq model path")
                model_i = i_DDPM(self.config.data.dataset)

The code segment starts from line 120, in which model_path = "dm_afhq_model.pth", where can I find this pth, where can I download it, this code can not run, hope you can help,Thank you very much for your model_path = "dm_afhq_model.pth", where can I find this pth, this code can not run, hope you can help, thank you very much！

**Comment by mac2win** [comment]
CUDA_VISIBLE_DEVICES=0,1 python main_afhq_train.py --attack              --config afhq.yml                     --exp ./runs_train_afhq_0122                  --n_test_img 4                         --t_0 500                               --n_inv_step 40                         --n_test_step 40      >> log_train_afhq_0122.txt
INFO - main_afhq_train.py - 2024-01-31 03:12:25,235 - Using device: cuda
INFO - main_afhq_train.py - 2024-01-31 03:12:25,236 - Exp instance id = 934
INFO - main_afhq_train.py - 2024-01-31 03:12:25,236 - Exp comment = 
INFO - main_afhq_train.py - 2024-01-31 03:12:25,236 - Config =
ERROR - main_afhq_train.py - 2024-01-31 03:12:28,428 - Traceback (most recent call last):
  File "main_afhq_train.py", line 325, in main
    runner.attack()
  File "/workspace/algorithm/adv_se/diffusionclip_afhq_train.py", line 128, in attack
    ckpt = torch.load(model_path)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'dm_afhq_model.pth'

**Comment by steven202** [comment]
Hi,

For all the model weights, I basically use model weights from DiffusionClip:
https://github.com/gwang-kim/DiffusionCLIP

For AFHQ dataset, the original model only has “dog” category. If you directly use the original model, you can only modify images into ones with dog features. In the appendix of our paper, we mentioned this. If you’d like to generate images with any of three categories, you need to train/fine-tune a model with three categories.

Hope this helps.

**Comment by mac2win** [comment]
Hello, this part of preparing diffusion model, which uses the weight of CelebA-HQ pre-trained diffusion model from DiffusionCLIP: IR-SE50, this model does not need to be modified, just put in the corresponding config, right?For the AFHQ dataset, use the diffusion model weight from ILVR+ADM: drive, which is the link to the Google cloud drive behind it, right?However, the weight model that it re-shares after the feeling there is a problem, can you share with me the weight file that you used to achieve this code?
Can you tell me how to train the AFHQ data set diffusion model from scratch?

**Comment by steven202** [comment]
For IR-SE50, I assume you could directly put it into the config. 
For afhq, as stated in the appendix of the paper, we can only generate dog images, so we didn't train it from scratch. Since we didn't train it from scratch, I cannot provide the code. 
We use model weights from https://github.com/gwang-kim/DiffusionCLIP. For AFHQ dataset, the model weights is trained on AFHQ-dog dataset. It should be there.
