### ISSUE TITLE
main_afhq_train error

### ISSUE THREAD

**Issue by Sourabs-kms** [steven202/semantic_adv_via_dm#6]
I want to train a dm_afhq_model.pth first, and then use it, but the startup command given in the code can not complete this operation correctly, please help me analyze how to achieve, first train this pth out, may I ask how this command is written?Or can you tell me how to write this command。

CUDA_VISIBLE_DEVICES=0 python main_afhq_train.py --attack  \
            --config afhq.yml         \
            --exp ./runs_train_afhq_test      \
            --n_test_img 4             \
            --t_0 500                   \
            --n_inv_step 40             \
            --n_test_step 40      >> log_train_afhq_test.txt
INFO - main_afhq_train.py - 2024-02-04 14:54:17,591 - Using device: cuda
INFO - main_afhq_train.py - 2024-02-04 14:54:17,592 - Exp instance id = 93519
INFO - main_afhq_train.py - 2024-02-04 14:54:17,592 - Exp comment = 
INFO - main_afhq_train.py - 2024-02-04 14:54:17,592 - Config =
ERROR - main_afhq_train.py - 2024-02-04 14:54:20,980 - Traceback (most recent call last):
  File "main_afhq_train.py", line 327, in main
    runner.attack()
  File "/workspace/algorithm/adv_se/diffusionclip_afhq_train.py", line 130, in attack
    ckpt = torch.load(model_path)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'dm_afhq_model.pth'

**Comment by steven202** [comment]
For afhq, as stated in the appendix of the paper, we can only generate dog images.
We use model weights from https://github.com/gwang-kim/DiffusionCLIP.
