### ISSUE TITLE
RuntimeError: value cannot be converted to type float without overflow

### ISSUE THREAD

**Issue by mac2win** [steven202/semantic_adv_via_dm#8]
Thank you for your work. While reproducing your code and fine-tuning the diffusion model for afhq, I encountered an error during the 389th iteration when running the code. The error message is "RuntimeError: value cannot be converted to type float without overflow" at the optimizer.step() stage.

I wanted to ask if you have encountered this issue during your training, and if so, how did you resolve it?

ERROR - main_afhq_train.py - 2024-02-22 11:19:45,883 - Traceback (most recent call last):
  File "main_afhq_train.py", line 327, in main
    runner.attack()
  File "/workspace/algorithm/adv_se/diffusionclip_afhq_train.py", line 343, in attack
    optim_ft.step()
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/optim/adam.py", line 141, in step
    F.adam(params_with_grad,
  File "/root/anaconda3/envs/kms/lib/python3.8/site-packages/torch/optim/_functional.py", line 110, in adam
    param.addcdiv_(exp_avg, denom, value=-step_size)
RuntimeError: value cannot be converted to type float without overflow

**Comment by steven202** [comment]
Hi, I didn't encountered the same problem during the training. 
For afhq, as stated in the appendix of the paper, we can only generate dog images. 
We use model weights from https://github.com/gwang-kim/DiffusionCLIP.
